### ISSUE TITLE
Filtering items by classes Inquisitor and Necromancer shows all items

### ISSUE THREAD

**Issue by Bonivur** [marius00/iagd#38] opened 2019-03-06 14:40 UTC
GDIA can't filter items by classes Inquisitor and Necromancer. When I tick the checkbox Inquisitor (for example) GDIA lists all items for all clasees instead. The filter for other classes  - Soldier, Nightblade etc works properly

**Comment by marius00** [comment] 2019-03-08 12:43
Addressed in ba8dbce3b7e33e87b3f4edb03ab65e2a25c01191

Re-open the issue if the issue is not resolved. (Included in the latest beta build)

**Closed by marius00** 2019-03-08 12:43 UTC
