### ISSUE TITLE
"Delaying stash loot" message when the game is minimized

### ISSUE THREAD

**Issue by okainov** [marius00/iagd#81] opened 2019-10-06 12:47 UTC
1. Run GD and IA
2. Walk near to the smuggler
3. Click "Esc" in the game, make sure game is paused
4. Minimize the game, switch to IA
5. Make sure annoying popup "Delaying stash loot" is appearing continuously

Please detect that the game is paused/minimized (or just when IA window is not in focus) and don't try to loot the stash then

**Comment by marius00** [comment] 2019-11-22 23:38
> or just when IA window is in focus

But that's sort of the main functionality of IA.

You expect items to be removed, while you're in-game and GD has focus.
You dump items, run off, farm more, and when you return the stash is empty and ready for you to dump more items in there.

**Comment by Eradev** [comment] 2021-08-14 21:54
Can't reproduce. Has it been fixed @marius00 ?

**Comment by marius00** [comment] 2021-08-15 05:51
I don't think so.. 

I read this as not being able to see the "X items looted" message when you only have one monitor. As the message will have faded away by the time you alt-tab into IA.

**Comment by marius00** [comment] 2022-02-12 12:01
Fixed in 56097712c20c0eee82b4369c7419a26a52003ad9

**Closed by marius00** 2022-02-12 12:01 UTC
Labels: good first issue, annoying
